const fabrics = {
  Patterns: {
    All: [
      'herringbone-off-white',
      'herringbone-light-gray',
      'herringbone-sand',
      'herringbone-denim',
      'herringbone-cerulean',
      'herringbone-charcoal-gray',
      'herringbone-dark-sage',
      'herringbone-mustard-yellow',
      'herringbone-light-sage',
      'woven-mosaic-storm-gray',
      'woven-mosaic-off-white',
      'camellia-cream',
      'camellia-lily-white',
      'camellia-sunset-orange',
      'pinstripe-dark-gray',
      'pinstripe-off-white',
      'sedona-ivory',
      'kali-ikat-blue',
      'houndstooth',
      'cowhide-black-and-white',
      'evergreen-forest',
      'mezzo-diamond-sapphire',
      'mezzo-diamond-grayscale',
      'shagreen-storm-gray',
      'staccato-salt-and-pepper',
      'gingham-powder-blue',
      'gingham-rustic-red',
    ],
    Abstract: ['woven-mosaic-storm-gray', 'woven-mosaic-off-white', 'staccato-salt-and-pepper'],
    Animal: ['cowhide-black-and-white', 'shagreen-storm-gray'],
    Floral: ['camellia-cream', 'camellia-lily-white', 'camellia-sunset-orange', 'evergreen-forest'],
    Textural: [
      'herringbone-off-white',
      'herringbone-light-gray',
      'herringbone-sand',
      'herringbone-denim',
      'herringbone-cerulean',
      'herringbone-charcoal-gray',
      'herringbone-dark-sage',
      'herringbone-mustard-yellow',
      'herringbone-light-sage',
    ],
    Geometric: [
      'pinstripe-dark-gray',
      'pinstripe-off-white',
      'sedona-ivory',
      'kali-ikat-blue',
      'houndstooth',
      'mezzo-diamond-sapphire',
      'mezzo-diamond-grayscale',
      'gingham-powder-blue',
      'gingham-rustic-red',
    ],
  },
  Solids: {
    All: [
      'off-white',
      'dusty-rose',
      'sand',
      'light-gray',
      'charcoal-gray',
      'ash-brown',
      'maroon',
      'chili-red',
      'burnt-orange',
      'mustard-yellow',
      'soft-chartreuse',
      'light-sage',
      'dark-sage',
      'arctic-blue',
      'cerulean',
      'dark-denim-blue',
    ],
    Neutral: ['off-white', 'sand', 'light-gray', 'charcoal-gray', 'ash-brown'],
    Cool: [
      'off-white',
      'light-gray',
      'soft-chartreuse',
      'light-sage',
      'dark-sage',
      'arctic-blue',
      'cerulean',
      'dark-denim-blue',
    ],
    Warm: [
      'dusty-rose',
      'sand',
      'mustard-yellow',
      'burnt-orange',
      'chili-red',
      'maroon',
      'ash-brown',
    ],
    Dark: ['charcoal-gray', 'dark-denim-blue', 'dark-sage', 'maroon', 'ash-brown'],
  },
};

export default fabrics;
