const bestSellingFabricsOrder = [
  'off white',
  'light gray',
  'sand',
  'dark denim blue',
  'cerulean',
  'charcoal gray',
  'herringbone off white',
  'dark sage',
  'mustard yellow',
  'burnt orange',
  'light sage',
  'herringbone light gray',
  'herringbone denim',
  'sedona ivory',
  'maroon',
  'herringbone charcoal gray',
  'chili red',
  'dusty rose',
  'kali ikat blue',
  'woven mosaic storm gray',
  'houndstooth',
  'arctic blue',
  'soft chartreuse',
  'cowhide black and white',
  'camellia cream',
  'camellia sunset orange',
  'ash brown',
  'pinstripe dark gray',
  'evergreen forest',
  'mezzo diamond sapphire',
  'shagreen storm gray',
  'staccato salt and pepper',
  'mezzo diamond grayscale',
  'gingham powder blue',
  'gingham rustic red',
  'herringbone sand',
  'herringbone cerulean',
  'herringbone mustard yellow',
  'herringbone dark sage',
  'herringbone light sage',
  'pinstripe off white',
  'woven mosaic off white',
  'camellia lily white',
];

export default bestSellingFabricsOrder;
