const chairCoverFabrics = [
  'off white',
  'dusty rose',
  'sand',
  'light gray',
  'charcoal gray',
  'ash brown',
  'maroon',
  'chili red',
  'burnt orange',
  'mustard yellow',
  'soft chartreuse',
  'light sage',
  'dark sage',
  'arctic blue',
  'cerulean',
  'dark denim blue',
  'herringbone denim',
  'herringbone off white',
  'herringbone light gray',
  'herringbone charcoal gray',
  'pinstripe dark gray',
  'houndstooth',
  'gingham powder blue',
  'sedona ivory',
  'kali ikat blue',
  'mezzo diamond grayscale',
  'mezzo diamond sapphire',
  'woven mosaic storm gray',
  'staccato salt and pepper',
  'shagreen storm gray',
  'cowhide black and white',
  'camellia sunset orange',
  'camellia cream',
  'gingham rustic red',
  'evergreen forest',
  'herringbone sand',
  'herringbone cerulean',
  'herringbone mustard yellow',
  'herringbone dark sage',
  'herringbone light sage',
  'pinstripe off white',
  'woven mosaic off white',
  'camellia lily white',
];

export default chairCoverFabrics;
