const fabrics = {
  All: {
    All: [
      'off-white',
      'sand',
      'dark-denim-blue',
      'light-gray',
      'charcoal-gray',
      'cerulean',
      'mustard-yellow',
      'dark-sage',
      'light-sage',
      'burnt-orange',
      'chili-red',
      'maroon',
      'dusty-rose',
      'arctic-blue',
      'soft-chartreuse',
      'ash-brown',
      'kali-ikat-blue',
      'sedona-ivory',
      'houndstooth',
      'herringbone-off-white',
      'herringbone-light-gray',
      'herringbone-sand',
      'herringbone-denim',
      'herringbone-cerulean',
      'herringbone-charcoal-gray',
      'herringbone-dark-sage',
      'herringbone-mustard-yellow',
      'herringbone-light-sage',
      'woven-mosaic-storm-gray',
      'woven-mosaic-off-white',
      'camellia-cream',
      'camellia-lily-white',
      'camellia-sunset-orange',
      'pinstripe-dark-gray',
      'pinstripe-off-white',
      'sedona-ivory',
      'kali-ikat-blue',
      'houndstooth',
      'cowhide-black-and-white',
      'evergreen-forest',
      'mezzo-diamond-sapphire',
      'mezzo-diamond-grayscale',
      'shagreen-storm-gray',
      'staccato-salt-and-pepper',
      'gingham-powder-blue',
      'gingham-rustic-red',
    ],
    White: [
      'off-white',
      'herringbone-off-white',
      'woven-mosaic-off-white',
      'camellia-cream',
      'camellia-lily-white',
      'pinstripe-off-white',
      'gingham-powder-blue',
    ],
    Gray: [
      'light-gray',
      'charcoal-gray',
      'herringbone-light-gray',
      'herringbone-charcoal-gray',
      'woven-mosaic-storm-gray',
      'pinstripe-dark-gray',
      'shagreen-storm-gray',
      'mezzo-diamond-grayscale',
    ],
    Blue: [
      'dark-denim-blue',
      'cerulean',
      'herringbone-denim',
      'herringbone-cerulean',
      'kali-ikat-blue',
      'arctic-blue',
      'mezzo-diamond-sapphire',
      'gingham-powder-blue',
    ],
    Green: [
      'dark-sage',
      'herringbone-dark-sage',
      'light-sage',
      'herringbone-light-sage',
      'soft-chartreuse',
      'evergreen-forest',
    ],
    Yellow: ['mustard-yellow', 'herringbone-mustard-yellow', 'kali-ikat-blue'],
    Orange: ['burnt-orange', 'camellia-sunset-orange'],
    Red: ['maroon', 'chili-red', 'dusty-rose', 'gingham-rustic-red'],
    Brown: ['sand', 'herringbone-sand', 'ash-brown'],
    Black: ['sedona-ivory', 'houndstooth', 'cowhide-black-and-white', 'staccato-salt-and-pepper'],
    Multi: [
      'herringbone-off-white',
      'herringbone-light-gray',
      'herringbone-sand',
      'herringbone-denim',
      'herringbone-cerulean',
      'herringbone-charcoal-gray',
      'herringbone-dark-sage',
      'herringbone-mustard-yellow',
      'herringbone-light-sage',
      'woven-mosaic-storm-gray',
      'woven-mosaic-off-white',
      'camellia-cream',
      'camellia-lily-white',
      'camellia-sunset-orange',
      'pinstripe-dark-gray',
      'pinstripe-off-white',
      'sedona-ivory',
      'kali-ikat-blue',
      'houndstooth',
      'cowhide-black-and-white',
      'evergreen-forest',
      'mezzo-diamond-sapphire',
      'mezzo-diamond-grayscale',
      'shagreen-storm-gray',
      'staccato-salt-and-pepper',
      'gingham-powder-blue',
      'gingham-rustic-red',
    ],
  },
  'Best Sellers': {
    All: [
      'off-white',
      'sand',
      'dark-denim-blue',
      'light-gray',
      'charcoal-gray',
      'cerulean',
      'mustard-yellow',
      'dark-sage',
      'kali-ikat-blue',
      'sedona-ivory',
      'houndstooth',
      'herringbone-off-white',
      'herringbone-light-gray',
      'herringbone-denim',
      'woven-mosaic-storm-gray',
      'herringbone-charcoal-gray',
      'cowhide-black-and-white',
    ],
  },
};

export default fabrics;
